### ISSUE TITLE
Chapter 11 - (11-ChapterBiasFairness.Rmd) - replace FP with FN

### ISSUE THREAD

**Issue by saleiro** [Coleridge-Initiative/big-data-and-social-science#25]
"-   If your intervention is assistive in nature (e.g., determining who
    should receive a food subsidy), individuals may be harmed by failing
    to intervene on them when they have need, so you may care more about
    metrics that focus on false positives."

Above should be false negatives.

**Comment by kimbrianj** [comment]
Should be fixed now. Thank you.
